### ISSUE TITLE
Exception when trying to edit Owner in react demo

### ISSUE THREAD

**Issue by alexbudarov** [cuba-guides/cuba-petclinic-online-demo#10]
- Open https://demo10.cuba-platform.com/petclinic-front/index.html#/ownerManagement
- Owners
- Edit one of owners
- Change any field, try to save changes

Actual:
Browser shows "Error" alert.

If you launch project locally, the same action prints this exception to log:
```
16:37:22.835 WARN  c.h.c.c.a.s.EntitySerialization         - Entity petclinic_Owner doesn't contain a '_instanceName' property
16:37:22.837 ERROR c.h.a.r.a.c.RestControllerExceptionHandler- Exception in REST controller
java.lang.RuntimeException: JsonArray was expected for property pets
	at com.haulmont.cuba.core.app.importexport.EntityImportViewBuilder.buildFromJsonObject(EntityImportViewBuilder.java:128) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.importexport.EntityImportViewBuilder.buildFromJson(EntityImportViewBuilder.java:57) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.getUpdatedEntity(EntitiesControllerManager.java:527) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.updateEntity(EntitiesControllerManager.java:459) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.controllers.EntitiesController.updateEntity(EntitiesController.java:138) ~[restapi-rest-api-7.2.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at ...

```

**Comment by alexbudarov** [comment]
PUT request json:
![image](https://user-images.githubusercontent.com/6158807/97004976-d7f93d00-154e-11eb-9c84-55496062fb55.png)
